### ISSUE TITLE
Job Solr.CoreTracker-archive threw an unhandled Exception: 

### ISSUE THREAD

**Issue by crimanvill** [atolcd/alfresco-trashcan-cleaner#10]
Hi, first I want to  say  Thanks for sharing the trash can module it is really helpull.

Im trying to  install the trashcan- cleaner on Alfresco Community 4.2.c (I  know it says on main page its for 4.2d but I'm hoping it works on c)  and Im getting some errors on log hope you can help me.

I instaled the amp, and modified alfresco-global with this:

Trigger at 4am each day
trashcan.cleaner.cron=0 1 4 \* \* ?
Duration, in days, during which deleted items will be protected
trashcan.cleaner.protected.day=5

What I'm I  doing wrong ?  Here an image of my log.

Hope you can help me ty.

![alfresco-log](https://cloud.githubusercontent.com/assets/13003872/8383099/426d08d4-1bfd-11e5-848a-96d360522777.png)

**Comment by bmagnier** [comment]
Hi,

From the log you attached, it seems the module is not correctly deployed : the application fails to find the class com.atolcd.alfresco.trashcancleaner.TrashcanCleanerJob, which is part of our sources.

Could you check the content of the AMP file you built, to ensure there is a non-empty JAR file in the lib directory ?

**Comment by crimanvill** [comment]
Hi, thx for you reply.

I didnt really built the AMP because I honestly dont know how to do it, I  got it from a link that found  here on the issues. 

I there a chance I can get the AMP from you ?  or instructions to build the AMP ?  From the download here I got a zip file.

Thanks in advance

**Comment by bmagnier** [comment]
From the ZIP you can download here, you could follow the [readme](https://github.com/atolcd/alfresco-trashcan-cleaner#building-the-module) to build the AMP.

Alternatively, this [link](https://buildhive.cloudbees.com/job/atolcd/job/alfresco-trashcan-cleaner/17/com.atolcd.alfresco$trashcan-cleaner/artifact/com.atolcd.alfresco/trashcan-cleaner/2.0.0/trashcan-cleaner-2.0.0.amp) should do the trick. It has been automatically built the last time we commited on this repository.

**Comment by crimanvill** [comment]
Thanks for you help.

 Im going to  try  again and will tell you how it goes.

**Comment by crimanvill** [comment]
Hi again, 

I  been trying with the amp file u sent me  and have the same error message. Any  ideas ?

**Comment by bmagnier** [comment]
Well, since the JAR file is in the module (and the missing class file is in the JAR), the only remaining options for this kind of error are a faulty module installation or a faulty Alfresco installation.

Can you check if you find the com.atolcd.alfresco.trashcan-cleaner-2.0.0.jar in your alfresco/WEB-INF/lib folder ?

**Comment by crimanvill** [comment]
Hey  thx for u answer.

The com.atolcd.alfresco.trashcan-cleaner-2.0.0.jar is in the web-inf/lib folder. 

Im usgin -verbose when trying to install to see the error description and  I can see there that  after he does the backup for the alfresco.war file  it shows **05300000 Unable to  load module details  from property file** so  Im guesing I  have to change the Alfresco  version on the Maven property alfresco.version.

Is this correct ? 

Thanks in advance

**Comment by bmagnier** [comment]
Well I'd say the module is not correctly installed, since you got an error.
Can you check the module.properties file from your AMP?
