### ISSUE TITLE
Null pointer exception at scheduled execution time

### ISSUE THREAD

**Issue by sobotkav** [atolcd/alfresco-trashcan-cleaner#2]
Hello,
I have successfuly compiled  and installed this module in Alfresco Community 4.2.c.

I have scheduled cleaner to launch at 9:14 in alfresco-global.properties like this:

trashcan.cleaner.cron=0 14 9 \* \* ?

I started alfresco and waited untill 9:14 and then I got an unhandled exception.

I followed installation steps exactly and did not get any errors during compile or deploy via MMT.

Is this an issue with Alfresco 4.2.c or did I messed up something? Happy to provide additional info.

Regards,
Vladimír Sobotka

EDIT: running alfresco on Debian Wheezy, uname -a: Linux a04111 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 GNU/Linux
## alfresco.log:

09:12:15,953 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'sysAdmin' subsystem, ID: [sysAdmin, default]
09:12:15,974 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'sysAdmin' subsystem, ID: [sysAdmin, default] complete
09:12:26,193 INFO  [org.springframework.extensions.webscripts.TemplateProcessorRegistry] Registered template processor Repository Template Processor for extension ftl
09:12:26,197 INFO  [org.springframework.extensions.webscripts.ScriptProcessorRegistry] Registered script processor Repository Script Processor for extension js
09:12:32,038 INFO  [org.alfresco.repo.domain.schema.SchemaBootstrap] Connecting to database: jdbc:mysql://localhost:3306/alfresco_4?characterEncoding=utf8, UserName=alfresco@localhost, MySQL Connector Java
09:12:32,039 INFO  [org.alfresco.repo.domain.schema.SchemaBootstrap] Schema managed by database dialect org.hibernate.dialect.MySQLInnoDBDialect.
09:12:32,504 INFO  [org.alfresco.repo.domain.schema.SchemaBootstrap] No changes were made to the schema.
09:12:33,349 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Search' subsystem, ID: [Search, managed, solr]
09:12:33,468 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Search' subsystem, ID: [Search, managed, solr] complete
09:12:33,678 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'thirdparty' subsystem, ID: [thirdparty, default]
09:12:33,756 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'thirdparty' subsystem, ID: [thirdparty, default] complete
09:12:33,756 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'OOoDirect' subsystem, ID: [OOoDirect, default]
09:12:34,081 WARN  [org.alfresco.util.OpenOfficeConnectionTester] An initial OpenOffice connection could not be established.
09:12:34,085 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'OOoDirect' subsystem, ID: [OOoDirect, default] complete
09:12:34,087 INFO  [org.alfresco.repo.admin.ConfigurationChecker] The Alfresco root data directory ('dir.root') is: /opt/alfresco-4.2.c/alf_data
09:12:34,107 INFO  [org.alfresco.repo.admin.patch.PatchExecuter] Checking for patches to apply ...
09:12:35,195 INFO  [org.alfresco.repo.admin.patch.PatchExecuter] No patches were required.
09:12:35,206 INFO  [org.alfresco.repo.module.ModuleServiceImpl] Found 2 module(s).
09:12:35,255 INFO  [org.alfresco.repo.module.ModuleServiceImpl] Starting module 'trashcan-cleaner' version 1.0.1.
09:12:35,292 INFO  [org.alfresco.repo.module.ModuleServiceImpl] Starting module 'org.alfresco.integrations.google.docs' version 2.0.1.
09:12:35,310 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'fileServers' subsystem, ID: [fileServers, default]
09:12:35,736 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Authentication' subsystem, ID: [Authentication, managed, alfrescoNtlm1]
09:12:35,845 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Authentication' subsystem, ID: [Authentication, managed, alfrescoNtlm1] complete
09:12:35,845 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Authentication' subsystem, ID: [Authentication, managed, ldap-ad1]
09:12:35,912 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Authentication' subsystem, ID: [Authentication, managed, ldap-ad1] complete
09:12:40,928 WARN  [org.alfresco.fileserver] CIFS, Unable to get local domain/workgroup name, using default of WORKGROUP. This may be due to firewall settings or incorrect <broadcast> setting)
09:12:40,961 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'fileServers' subsystem, ID: [fileServers, default] complete
09:12:40,961 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'imap' subsystem, ID: [imap, default]
09:12:41,109 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'imap' subsystem, ID: [imap, default] complete
09:12:41,109 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'email' subsystem, ID: [email, outbound]
09:12:41,150 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'email' subsystem, ID: [email, outbound] complete
09:12:41,150 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'email' subsystem, ID: [email, inbound]
09:12:41,225 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'email' subsystem, ID: [email, inbound] complete
09:12:41,225 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'googledocs' subsystem, ID: [googledocs, default]
09:12:41,274 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'googledocs' subsystem, ID: [googledocs, default] complete
09:12:41,274 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Subscriptions' subsystem, ID: [Subscriptions, default]
09:12:41,286 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Subscriptions' subsystem, ID: [Subscriptions, default] complete
09:12:41,286 INFO  [org.alfresco.repo.usage.UserUsageTrackingComponent] Disabled - clear non-missing user usages ...  
09:12:41,312 INFO  [org.alfresco.repo.usage.UserUsageTrackingComponent] Found 0 users to clear  
09:12:41,312 INFO  [org.alfresco.repo.usage.UserUsageTrackingComponent] ... cleared non-missing usages for 0 users  
09:12:41,312 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Synchronization' subsystem, ID: [Synchronization, default]  
09:12:41,368 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] Synchronizing users and groups with user registry 'ldap-ad1'  
09:12:41,389 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] Retrieving groups changed since Jul 9, 2013 10:58:24 AM from user registry 'ldap-ad1'  
09:12:41,424 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] ldap-ad1 Group Analysis: Commencing batch of 0 entries  
09:12:41,426 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] ldap-ad1 Group Analysis: Completed batch of 0 entries  
09:12:41,431 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] Retrieving users changed since Jul 10, 2013 8:44:48 AM from user registry 'ldap-ad1'  
09:12:41,543 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] ldap-ad1 User Creation and Association: Commencing batch of 0 entries  
09:12:41,544 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] ldap-ad1 User Creation and Association: Completed batch of 0 entries  
09:12:41,608 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] Finished synchronizing users and groups with user registry 'ldap-ad1'  
09:12:41,609 INFO  [org.alfresco.repo.security.sync.ChainingUserRegistrySynchronizer] 0 user(s) and 0 group(s) processed  
09:12:41,634 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Synchronization' subsystem, ID: [Synchronization, default] complete  
09:12:41,697 INFO  [org.alfresco.service.descriptor.DescriptorService] Alfresco JVM - v1.7.0_07-b10; maximum heap size 910.250MB  
09:12:41,698 INFO  [org.alfresco.service.descriptor.DescriptorService] Alfresco started (Community). Current version: 4.2.0 (4576) schema 6,022. Originally installed version: 4.2.0 (4576) schema 6,022.  
09:12:41,699 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'ActivitiesFeed' subsystem, ID: [ActivitiesFeed, default]  
09:12:41,776 WARN  [org.alfresco.util.AbstractTriggerBean] Job feedNotifierTrigger is not enabled  
09:12:41,777 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'ActivitiesFeed' subsystem, ID: [ActivitiesFeed, default] complete  
09:12:41,777 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'Replication' subsystem, ID: [Replication, default]  
09:12:41,793 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'Replication' subsystem, ID: [Replication, default] complete  
09:12:43,200 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Starting 'googledocs' subsystem, ID: [googledocs, v2]  
09:12:43,263 INFO  [org.alfresco.repo.management.subsystems.ChildApplicationContextFactory] Startup of 'googledocs' subsystem, ID: [googledocs, v2] complete  
09:12:49,076 INFO  [org.springframework.extensions.webscripts.DeclarativeRegistry] Registered 486 Web Scripts (+0 failed), 766 URLs  
09:12:49,076 INFO  [org.springframework.extensions.webscripts.DeclarativeRegistry] Registered 2 Package Description Documents (+0 failed)  
09:12:49,076 INFO  [org.springframework.extensions.webscripts.DeclarativeRegistry] Registered 1 Schema Description Documents (+0 failed) 
09:12:49,079 INFO  [org.springframework.extensions.webscripts.AbstractRuntimeContainer] Initialised Repository Web Script Container (in 5788.699ms)
09:12:49,098 INFO  [org.springframework.extensions.webscripts.TemplateProcessorRegistry] Registered template processor freemarker for extension ftl
09:12:49,099 INFO  [org.springframework.extensions.webscripts.ScriptProcessorRegistry] Registered script processor javascript for extension js
09:13:00,095 WARN  [org.alfresco.util.OpenOfficeConnectionTester] Error trying to query Open Office version information. OpenOffice.org's ConfigurationRegistry not implemented in this version of OOo. This should not affect the operation of OOo.
09:13:00,097 INFO  [org.alfresco.util.OpenOfficeConnectionTester] The OpenOffice connection was re-established.
09:14:00,013 ERROR [org.quartz.core.JobRunShell] Job DEFAULT.trashcanCleanerJobDetail threw an unhandled Exception: 
java.lang.NullPointerException
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleaner.execute(TrashcanCleaner.java:119)
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleanerJob$1.doWork(TrashcanCleanerJob.java:32)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:529)
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleanerJob.execute(TrashcanCleanerJob.java:25)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
09:14:00,014 ERROR [org.quartz.core.ErrorLogger] Job (DEFAULT.trashcanCleanerJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:227)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
Caused by: java.lang.NullPointerException
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleaner.execute(TrashcanCleaner.java:119)
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleanerJob$1.doWork(TrashcanCleanerJob.java:32)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:529)
        at com.atolcd.alfresco.trashcancleaner.TrashcanCleanerJob.execute(TrashcanCleanerJob.java:25)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        ... 1 more

**Comment by tomekszy** [comment]
I have similar problem, i got in my log:

2016-11-03 04:00:00,388 ERROR [org.quartz.core.JobRunShell] [DefaultScheduler_Worker-6] Job DEFAULT.tempFileCleanerJobDetail#1 threw an unhandled Exception: 
java.lang.NullPointerException
	at org.alfresco.trashcan.TrashcanCleaner.olderThanDaysToKeep(TrashcanCleaner.java:102)
	at org.alfresco.trashcan.TrashcanCleaner.fillBatchToDelete(TrashcanCleaner.java:84)
	at org.alfresco.trashcan.TrashcanCleaner.getBatchToDelete(TrashcanCleaner.java:75)
	at org.alfresco.trashcan.TrashcanCleaner.clean(TrashcanCleaner.java:48)
	at org.alfresco.trashcan.TrashcanCleanerJob$1.execute(TrashcanCleanerJob.java:36)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:326)
	at org.alfresco.trashcan.TrashcanCleanerJob.cleanInTransaction(TrashcanCleanerJob.java:40)
	at org.alfresco.trashcan.TrashcanCleanerJob.executeJob(TrashcanCleanerJob.java:29)
	at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:93)
	at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:71)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2016-11-03 04:00:00,391 ERROR [org.quartz.core.ErrorLogger] [DefaultScheduler_Worker-6] Job (DEFAULT.tempFileCleanerJobDetail#1 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:227)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
Caused by: java.lang.NullPointerException
	at org.alfresco.trashcan.TrashcanCleaner.olderThanDaysToKeep(TrashcanCleaner.java:102)
	at org.alfresco.trashcan.TrashcanCleaner.fillBatchToDelete(TrashcanCleaner.java:84)
	at org.alfresco.trashcan.TrashcanCleaner.getBatchToDelete(TrashcanCleaner.java:75)
	at org.alfresco.trashcan.TrashcanCleaner.clean(TrashcanCleaner.java:48)
	at org.alfresco.trashcan.TrashcanCleanerJob$1.execute(TrashcanCleanerJob.java:36)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:326)
	at org.alfresco.trashcan.TrashcanCleanerJob.cleanInTransaction(TrashcanCleanerJob.java:40)
	at org.alfresco.trashcan.TrashcanCleanerJob.executeJob(TrashcanCleanerJob.java:29)
	at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:93)
	at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:71)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	... 1 more

My settings from alfresco-global.properties are:

# Alfresco Trashcan Cleaner AMP
system.content.eagerOrphanCleanup=true
trashcan.cron=0 0 4 * * ?
trashcan.daysToKeep=1
trashcan.deleteBatchCount=1000
log4j.logger.org.alfresco.trashcan=debug
# Trigger at 4am each day
trashcan.cleaner.cron=0 0 4 * * ?

# Duration, in days, during which deleted items will be protected
trashcan.cleaner.protected.day=1

I think it could be related with bad settings in alfresco-global.properties, but I don't know which are proper. I tried to change the storeUrl parameter in services-context.xml file, but I couldn't find store Url parameter.
My Alfresco version is Community-5.1.0, and i use trashcan AMP version 1.2

**Comment by jberthoux** [comment]
Hi tomekszy,

Firstly thank you to use the trashcan cleaner module.

I think you should use a more recent version of the module. You wrote :

> i use trashcan AMP version 1.2

The module is now in version 2.0.0. Let me know if you still have troubles after install the lastest version of the module.

Regards,
Julien
