### ISSUE TITLE
Do not run and no logs

### ISSUE THREAD

**Issue by Cephinet** [atolcd/alfresco-trashcan-cleaner#8]
Hello,
I am new in Alfresco ;-)
I am trying to use Trashcan Cleaner on Alfresco Community 5.0.c.
I have create succesfufy the AMP file with "vmn package" command and install it with this command :

> > java -jar D:\Alfresco\bin\alfresco-mmt.jar install D:\Alfresco\amps\com.atolcd.alfresco.trashcan-cleaner-2.0.0.amp D:\Alfresco\tomcat\webapps\alfresco.war -force
> > I have modified the "tomcat\shared\classes\alfresco-global.properties" file with these parameters :
> > trashcan.cleaner.cron=0 0/15 \* \* \* ?
> > trashcan.cleaner.protected.day=0
> > I set trashcan.cleaner.protected.day to 0 to see quickly if that work.
> > To log, i have modified the "tomcat\webapps\alfresco\WEB-INF\classes\log4j.properties" with this parameter : 
> > log4j.logger.com.atolcd.alfresco.trashcancleaner=debug
> > After restart Alfresco, Trash is not empty and no log in logs files
> > Can you help to understand what i missed?
> > Thanks in advance

**Comment by jberthoux** [comment]
Hello,

firstly, thanks to use our module.
I think the trash is still full because, has your can see [here](https://github.com/atolcd/alfresco-trashcan-cleaner/blob/master/src/main/java/com/atolcd/alfresco/trashcancleaner/TrashcanCleaner.java) line 60, the `protectedDays`  value must be greater than 0. You should try with 1 instead of 0.
If you want to see all logs, you can use this parameter: `log4j.logger.com.atolcd.alfresco.trashcancleaner=all`

Regards

**Comment by Cephinet** [comment]
Hello Julien,
Many thanks for your quick answer.
I set to 1 the protectedDays and the log to all.
But nothing appears in logs file and the trash is not emptied. I have in it a file which is deleted since more than 1 day but it stay in the trash.
Any ideas?
Thanks in advance.
Regards

**Comment by jberthoux** [comment]
Hi,

it's possible that your archive store is not indexed. Can you set `workspace://SpacesStore` for the `storeUrl` parameter in "config/context/service-context.xml" and see it happens?

Regards

**Comment by Cephinet** [comment]
Hi,
I just do that and recreate amp file and install it.
After restarting server, nothing appears in logs file and the trash was not emptied :-(
Regards

**Comment by mathieuga** [comment]
Hello,
Trashcan-cleaner work in my défaut Alfresco community 5.0.c on W7.

My alfresco-global.properties :

# run trashcan cleaner at 04h00 am each day
trashcan.cleaner.cron=0 0 4 * * ?
# Duration, in days, during which deleted items will be protected
trashcan.cleaner.protected.day=1

Regards

**Comment by Cephinet** [comment]
Hello,

Thanks a lot for your time.
I will try on a new VM and see.
Regards

Cordialement / Regards,
Pascal Ruelle - Cephinet 

 


Web : 
http://www.cephinet.info
Mail : 
pascal.ruelle@cephinet.info
Fixe : 
+33 981 717 718
Mobile : 
+33 617 971 189
Fax : 
+33 972 118 228


Do not print this message unless it is necessary, consider the 
environment.
N'imprimez ce message que si nécessaire, pensez à l'environnement.




De :    MathieuGa <notifications@github.com>
A :     atolcd/alfresco-trashcan-cleaner 
<alfresco-trashcan-cleaner@noreply.github.com>
Cc :    Cephinet <pascal.ruelle@cephinet.info>
Date :  17/03/2015 15:38
Objet : Re: [alfresco-trashcan-cleaner] Do not run and no logs (#8)



Hello,
Trashcan-cleaner work in my défaut Alfresco community 5.0.c on W7.

My alfresco-global.properties :

# run trashcan cleaner at 04h00 am each day
trashcan.cleaner.cron=0 0 4 * * ?
# Duration, in days, during which deleted items will be protected
trashcan.cleaner.protected.day=1

Regards
Le 13 mars 2015 14:40, "Cephinet" <notifications@github.com> a écrit :

> Hi,
> I just do that and recreate amp file and install it.
> After restarting server, nothing appears in logs file and the trash was
> not emptied :-(
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/atolcd/alfresco-trashcan-cleaner/issues/8#issuecomment-78974390
