### ISSUE TITLE
Did you test trashcan cleaner works with Alfresco 4.2.4 or 5.x ? 

### ISSUE THREAD

**Issue by CesarCapillas** [atolcd/alfresco-trashcan-cleaner#9]
The info provided in the main page:

Works with:

Alfresco Community from 4.2.d
Alfresco Enterprise from 4.1.5

Did you now if there exist any incompatibility with newer versions ?

Thanks in advance.

--C.

**Comment by jberthoux** [comment]
Hello,

to my knowledge, there is no kown incompatibilities with newer enterprise / community version.

Regards,
Julien

**Comment by CesarCapillas** [comment]
Thanks Julien.

--C.
